name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Configure SSH hosts
        run: ssh-keyscan -H app.collabfinder.net >> ~/.ssh/known_hosts
      - name: Deploy with deployer
        env:
          DEPLOYER_PATH: ${{ secrets.DEPLOYER_PATH }}
          DEPLOYER_USER: ${{ secrets.DEPLOYER_USER }}
          DEPLOYER_ENV_PATH: ${{ secrets.DEPLOYER_ENV_PATH }}
          NPM_BIN: ${{ secrets.NPM_BIN }}
        run: vendor/bin/dep deploy
